# Dockerfile
FROM markhobson/maven-chrome:latest

# Set the working directory
WORKDIR /src/test/java/basicweb

# Copy the POM file
COPY pom.xml .

# Copy the source code
COPY src src
RUN mvn clean install
